name: Spotify Data Tracker

on:
  schedule:
    # Run multiple times a day (adjust times as needed)
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: # Allow manual runs

jobs:
  fetch-spotify-data:
    runs-on: ubuntu-latest

    steps:
    #  Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    #Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv pandas

    #Run the script
    - name: Run fetch_spotify_history.py
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: python fetch_spotify_history.py

#Commit changes
 - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add spotify_history.csv
        git commit -m "Update Spotify data [skip ci]" || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/katemcgraw0/spotify-data-tracker.git main
